//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace duck_fed.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duck
    {
        public int Id { get; set; }
        public string FoodName { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> FoodType { get; set; }
        public string Amount { get; set; }
        public int DuckNum { get; set; }
        public string Location { get; set; }
    }
}
